-- =====================================================================
-- Website Analytics — what the storefront records, and what the admin reads
--
-- RUN THIS IN THE **WEBSITE'S** SUPABASE PROJECT, not the platform's.
-- It is the same project the chat, the reviews and the site settings
-- live in. It is safe to run again, and again after that.
--
-- THIS FILE ONLY ADDS. It creates three tables, one small presence
-- table, their indexes, their policies and nine functions. It does not
-- replace, alter or drop anything that was here before it — no existing
-- table, no existing policy, and in particular not my_access(), which
-- every page in the admin depends on to sign anybody in at all. The one
-- thing it writes to an existing row is a permission tick that was not
-- there before, and it writes that only where nobody has set it.
--
-- WHAT IS RECORDED, PLAINLY. A visit is four things: a random token for
-- the browser, a random token for the visit, which page, and when. Not
-- an internet address — a page cannot see one. Not a browser string —
-- only 'mobile', 'tablet' or 'desktop', worked out in the browser and
-- the original thrown away. Not a name, not an email, not an account,
-- not a cart. Read by a stranger, a row says "somebody looked at
-- /shop at 14:32 on a phone" and nothing whatever about who.
--
-- The two tokens are made by the browser out of random numbers. They are
-- not derived from anything about the person and mean nothing anywhere
-- else in the world. Clearing site data ends them, and the visitor
-- counts as somebody new — which is the honest answer, because after
-- that there is genuinely no way to tell.
--
-- ANYONE MAY WRITE A VISIT. NOBODY MAY READ ONE BACK. A storefront has
-- only the public key, so recording has to be open to it. Reading is
-- refused to everyone except an administrator whose role has been given
-- Website Analytics in Settings > Users & Roles, and that is enforced
-- here, in the database, not merely by the admin page hiding a tab.
--
-- WHY THERE ARE THREE TABLES AND NOT ONE. site_events is the raw record
-- and answers everything, but counting a year of it on every page load
-- would get slower every month. So each day, once it is over, is
-- summed into site_daily and its visitors listed in site_visitor_days,
-- and every question after that reads those instead. The day that is
-- still running is read raw, because it is the only day that can still
-- change. Nothing schedules this: the first read that notices a
-- finished day has no summary builds it, once, and every read after
-- that is arithmetic on a handful of rows.
--
-- RUNNING THIS IS OPTIONAL, AND SO IS KEEPING IT. Without it the
-- storefront records nothing, says nothing about it, and behaves in
-- every other respect exactly as it does now. The last section of this
-- file removes all of it in four lines.
-- =====================================================================


-- ---------------------------------------------------------------------
-- STEP 1. The raw record.
--
-- One row per thing a visitor did. Append only: there is no policy that
-- updates or deletes a row, and the grants below take the right away as
-- well, so a visit once recorded cannot be quietly edited into a better
-- number by anybody at all — including an administrator.
-- ---------------------------------------------------------------------
create table if not exists public.site_events (
  id       bigint generated by default as identity primary key,
  at       timestamptz not null default now(),
  kind     text        not null,   -- page_view | product_view | add_to_cart | checkout_start
  path     text,                   -- '/shop' — never the query string, never the hash
  label    text,                   -- what the page or the piece is called
  sku      text,                   -- set on the three product events, null on the rest
  visitor  text        not null,   -- random, this site only, means nothing elsewhere
  session  text        not null,   -- random, one visit
  device   text,                   -- mobile | tablet | desktop
  is_new   boolean     not null default false,
  referrer text                    -- the sending site's host and nothing more
);

comment on table public.site_events is
  'One row per page view, product view, add to cart or checkout start. Holds no name, no address, no account and no internet address: a random token for the browser, a random token for the visit, and what was looked at.';

-- The indexes, and what each one is for. Every question the admin asks
-- is "between these two moments", so `at` leads all of them.
create index if not exists se_at        on public.site_events (at desc);
create index if not exists se_kind_at   on public.site_events (kind, at desc);
create index if not exists se_visitor   on public.site_events (visitor, at desc);
create index if not exists se_session   on public.site_events (session, at desc);
-- Most-viewed pieces: a partial index, because three quarters of the
-- table has no sku and there is no reason to carry it in here.
create index if not exists se_sku_at    on public.site_events (sku, at desc) where sku is not null;
-- Most-viewed pages: only page views are ever grouped by path.
create index if not exists se_path_at   on public.site_events (path, at desc) where kind = 'page_view';


-- ---------------------------------------------------------------------
-- STEP 2. The day, once it is over.
--
-- site_daily holds the counts that can be added up. site_visitor_days
-- holds the ones that cannot: two visits by the same browser on Monday
-- and Tuesday are two rows there and one visitor over the week, which
-- is the whole reason it exists — adding Monday's visitors to Tuesday's
-- gives a number that is always too big and never says by how much.
-- ---------------------------------------------------------------------
create table if not exists public.site_daily (
  day                date        primary key,
  tz                 text        not null,   -- the shop's timezone when this was built
  visits             integer     not null default 0,
  page_views         integer     not null default 0,
  product_views      integer     not null default 0,
  add_to_cart        integer     not null default 0,
  checkout_starts    integer     not null default 0,
  visitors           integer     not null default 0,
  new_visitors       integer     not null default 0,
  mobile             integer     not null default 0,
  desktop            integer     not null default 0,
  tablet             integer     not null default 0,
  built_at           timestamptz not null default now()
);

comment on column public.site_daily.tz is
  'The timezone the day was cut on. A shop that moves timezone leaves rows here cut on the old one, so every read checks this column and rebuilds the day rather than quietly answering in the wrong day.';

create table if not exists public.site_visitor_days (
  day      date    not null,
  visitor  text    not null,
  is_first boolean not null default false,   -- their first day here, ever
  primary key (day, visitor)
);

-- "Is this browser new?" is asked of a single visitor, so it needs its
-- own index: the primary key leads on day and cannot answer it.
create index if not exists svd_visitor on public.site_visitor_days (visitor);


-- ---------------------------------------------------------------------
-- STEP 3. Who is here right now.
--
-- One row per visit, overwritten every minute the tab is open and in
-- front of somebody. It is kept apart from site_events on purpose:
-- folding a heartbeat into the record would put a row in the permanent
-- table every minute per visitor and drown the thing it was meant to
-- measure. Here, a visit is one row however long it lasts, and the
-- rows are cleared out as they go stale.
-- ---------------------------------------------------------------------
create table if not exists public.site_presence (
  session text        primary key,
  seen_at timestamptz not null default now(),
  device  text
);
create index if not exists sp_seen on public.site_presence (seen_at desc);

comment on table public.site_presence is
  'Who is on the site in the last few minutes. One row per open visit, replaced as it beats, deleted once stale. Holds no visitor token and nothing that outlives the visit.';


-- ---------------------------------------------------------------------
-- STEP 4. Who may read any of it.
--
-- The same shape as chat_may_answer(): the owner always, and anybody
-- whose role has been given the tick. Asked by every reading function
-- below, so the answer is the database's and not the page's.
-- ---------------------------------------------------------------------
create or replace function public.may_see_analytics()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin()
     and coalesce((select a.active from public.admins a where a.id = auth.uid()), true)
     and (
       public.is_shop_owner()
       or coalesce(
            (select (s.data->(select coalesce(a.role,'agent') from public.admins a
                                where a.id = auth.uid())->'permissions'->>'analytics')::boolean
               from public.site_settings s where s.key = 'roles'),
            false)
     );
$$;


-- ---------------------------------------------------------------------
-- STEP 5. The rules.
--
-- Recording is open, because a storefront carries only the public key
-- and there is nowhere else for it to record from. What it may write is
-- fenced in by the checks below rather than trusted: a kind that is not
-- one of the four, a token of the wrong length, a path longer than any
-- real one or a time that is not roughly now are all refused by the
-- database and never reach the table.
--
-- Reading is refused to everybody except may_see_analytics(). Changing
-- and deleting are refused to everybody full stop — there is no policy
-- for either, and with row level security on, what is not permitted is
-- refused.
-- ---------------------------------------------------------------------
alter table public.site_events        enable row level security;
alter table public.site_visitor_days  enable row level security;
alter table public.site_daily         enable row level security;
alter table public.site_presence      enable row level security;

drop policy if exists se_write on public.site_events;
create policy se_write
  on public.site_events
  for insert
  to anon, authenticated
  with check (
        kind in ('page_view', 'product_view', 'add_to_cart', 'checkout_start')
    and length(visitor) between 8 and 64
    and length(session) between 8 and 64
    and (path     is null or length(path)     <= 300)
    and (label    is null or length(label)    <= 200)
    and (sku      is null or length(sku)      <= 64)
    and (referrer is null or length(referrer) <= 120)
    and (device   is null or device in ('mobile', 'tablet', 'desktop'))
    -- A batch held back while the tab was in the background may be a few
    -- minutes late, and a browser's clock may be wrong. Neither is a
    -- reason to accept a row dated last year or next week.
    and at > now() - interval '6 hours'
    and at < now() + interval '1 hour'
  );

drop policy if exists se_read on public.site_events;
create policy se_read
  on public.site_events
  for select
  to authenticated
  using (public.may_see_analytics());

-- Nobody writes this table directly, not even the storefront. A
-- heartbeat is an upsert, and an upsert under row level security has to
-- read the row it might be replacing — which would mean giving the
-- storefront permission to SELECT from here, and one visitor able to
-- read the presence table can count the shop's live traffic all day.
-- So the only way in is site_beat() below, which is allowed to write
-- this table and does not let anybody read a word of it.
drop policy if exists sp_write on public.site_presence;
drop policy if exists sp_beat  on public.site_presence;

drop policy if exists sp_read on public.site_presence;
create policy sp_read
  on public.site_presence
  for select
  to authenticated
  using (public.may_see_analytics());

-- The two summary tables are written by the rollup function below, which
-- runs as its definer. Nobody reads them directly either: every number
-- in the admin comes back through a function, so there is one place
-- where permission is checked and not four.
drop policy if exists sd_read on public.site_daily;
create policy sd_read
  on public.site_daily
  for select
  to authenticated
  using (public.may_see_analytics());

drop policy if exists svd_read on public.site_visitor_days;
create policy svd_read
  on public.site_visitor_days
  for select
  to authenticated
  using (public.may_see_analytics());

-- Said out loud rather than left to the policies. A missing policy and a
-- revoked grant refuse the same thing; saying both means a policy added
-- carelessly later cannot hand the right back on its own.
revoke update, delete on public.site_events       from anon, authenticated;
revoke insert, update, delete on public.site_daily        from anon, authenticated;
revoke insert, update, delete on public.site_visitor_days from anon, authenticated;
revoke insert, update, delete on public.site_presence from anon, authenticated;
grant  insert on public.site_events   to anon, authenticated;


-- ---------------------------------------------------------------------
-- STEP 5b. The heartbeat.
--
-- The one thing the storefront is allowed to write besides an event, and
-- it is a function rather than a table so that writing a beat cannot be
-- turned into reading the beats of everybody else.
--
-- It takes a random visit token and a device word, checks both, and
-- moves one timestamp. It returns nothing: there is no answer a
-- storefront needs and none it should be given. Called at most once a
-- minute by a tab that is actually in front of somebody.
-- ---------------------------------------------------------------------
create or replace function public.site_beat(p_session text, p_device text default null)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  if p_session is null or length(p_session) not between 8 and 64 then return; end if;
  if p_device is not null and p_device not in ('mobile', 'tablet', 'desktop') then
    p_device := null;
  end if;

  insert into public.site_presence (session, seen_at, device)
  values (p_session, now(), p_device)
  on conflict (session) do update
    set seen_at = now(),
        device  = coalesce(excluded.device, public.site_presence.device);
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 6. Summing up a day that is over.
--
-- Never today: today can still change, so it is always read raw. A day
-- with no traffic gets a row of zeros, which is a true answer and the
-- one the chart needs — a gap and a quiet Sunday are not the same thing.
-- ---------------------------------------------------------------------
create or replace function public.site_rollup(p_day date, p_tz text)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_start timestamptz;
  v_end   timestamptz;
begin
  if p_day is null or coalesce(p_tz, '') = '' then return; end if;
  if p_day >= (now() at time zone p_tz)::date then return; end if;

  v_start := (p_day::timestamp) at time zone p_tz;
  v_end   := ((p_day + 1)::timestamp) at time zone p_tz;

  -- Who was here that day. One row per browser per day, and no more:
  -- this is the table that makes "how many people over a week" a
  -- question with an exact answer instead of a sum that overcounts.
  insert into public.site_visitor_days (day, visitor, is_first)
  select p_day, e.visitor, false
    from public.site_events e
   where e.at >= v_start and e.at < v_end
   group by e.visitor
  on conflict (day, visitor) do nothing;

  -- Whether that day was their first, worked out from the record rather
  -- than taken from the browser's word for it.
  --
  -- CORRECTED ACROSS EVERY DAY THOSE VISITORS APPEAR ON, and this is the
  -- whole reason the statement is shaped this way. Days are not
  -- necessarily summed up in order: an owner who opens "Last 7 days" and
  -- then "This month" has this file build the later days first and the
  -- earlier ones after. A visitor first seen on the 1st and back on the
  -- 5th would have been marked first-ever on the 5th — because on the
  -- day the 5th was summed, the 1st was not yet on file — and would have
  -- gone on being counted as somebody new for ever.
  --
  -- So summing any day re-asks the question for every day those same
  -- visitors appear on, and writes only the rows whose answer changed.
  with touched as (
    select distinct visitor from public.site_visitor_days where day = p_day
  ),
  firsts as (
    select d.visitor, min(d.day) as first_day
      from public.site_visitor_days d
      join touched t on t.visitor = d.visitor
     group by d.visitor
  )
  update public.site_visitor_days d
     set is_first = (f.first_day = d.day)
    from firsts f
   where f.visitor = d.visitor
     and d.is_first is distinct from (f.first_day = d.day);

  -- And any day whose stored count of new visitors has just been made
  -- wrong by that correction is put right with it. Nothing the admin
  -- shows reads this column — new against returning is counted from
  -- site_visitor_days, where it can be counted exactly over a range —
  -- but a stored number that disagrees with the table it came from is a
  -- trap for whoever reads it next.
  update public.site_daily s
     set new_visitors = (select count(*)
                           from public.site_visitor_days d
                          where d.day = s.day and d.is_first)
   where s.day in (select distinct day
                     from public.site_visitor_days
                    where visitor in (select visitor from public.site_visitor_days
                                       where day = p_day));

  insert into public.site_daily as t (
    day, tz, visits, page_views, product_views, add_to_cart, checkout_starts,
    visitors, new_visitors, mobile, desktop, tablet, built_at)
  select
    p_day,
    p_tz,
    count(distinct e.session),
    count(*) filter (where e.kind = 'page_view'),
    count(*) filter (where e.kind = 'product_view'),
    count(*) filter (where e.kind = 'add_to_cart'),
    count(*) filter (where e.kind = 'checkout_start'),
    count(distinct e.visitor),
    (select count(*) from public.site_visitor_days d
      where d.day = p_day and d.is_first),
    -- Devices are counted per VISIT, not per event, so a visitor who
    -- reads nine pages on a phone is one phone and not nine.
    count(distinct e.session) filter (where e.device = 'mobile'),
    count(distinct e.session) filter (where e.device = 'desktop'),
    count(distinct e.session) filter (where e.device = 'tablet'),
    now()
    from public.site_events e
   where e.at >= v_start and e.at < v_end
  on conflict (day) do update set
    tz              = excluded.tz,
    visits          = excluded.visits,
    page_views      = excluded.page_views,
    product_views   = excluded.product_views,
    add_to_cart     = excluded.add_to_cart,
    checkout_starts = excluded.checkout_starts,
    visitors        = excluded.visitors,
    new_visitors    = excluded.new_visitors,
    mobile          = excluded.mobile,
    desktop         = excluded.desktop,
    tablet          = excluded.tablet,
    built_at        = now();
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 7. Making sure a range has its summaries, without a scheduler.
--
-- The first read that notices a finished day with no summary builds it,
-- once. Everything after that is arithmetic over a few rows.
--
-- TWO THINGS IT WILL NOT DO, and both matter. It will not build a day
-- earlier than the oldest event still on file — after old raw rows have
-- been pruned that day's real summary is already here, and rebuilding it
-- from an empty table would replace real history with zeros. And it
-- skips any day that already has a summary cut on this timezone, so the
-- work happens once and not once per page load.
-- ---------------------------------------------------------------------
create or replace function public.site_rollup_range(p_from date, p_to date, p_tz text)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_last date;
  v_min  date;
  d      date;
begin
  if p_from is null or p_to is null or coalesce(p_tz, '') = '' then return; end if;
  v_last := least(p_to, (now() at time zone p_tz)::date - 1);
  if v_last < p_from then return; end if;

  -- min(at) uses the index; putting the timezone conversion outside the
  -- aggregate is what keeps it able to.
  select (min(e.at) at time zone p_tz)::date into v_min from public.site_events e;
  if v_min is null then return; end if;

  for d in
    select g::date
      from generate_series(greatest(p_from, v_min)::timestamp,
                           v_last::timestamp, interval '1 day') g
  loop
    if not exists (select 1 from public.site_daily s where s.day = d and s.tz = p_tz) then
      perform public.site_rollup(d, p_tz);
    end if;
  end loop;
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 8. The numbers on the cards.
--
-- Whole days in the shop's own timezone, inclusive at both ends. Days
-- that are over are read from the summaries; the day still running is
-- read raw, because it is the only one that can still change.
-- ---------------------------------------------------------------------
create or replace function public.site_stats(p_from date, p_to date, p_tz text)
returns json
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_today   date;
  v_to      date;
  v_last    date;
  v_partial boolean;
  v_ps      timestamptz;
  v_pe      timestamptz;
  r_sum     record;
  r_now     record;
  v_people  integer := 0;
  v_new     integer := 0;
begin
  if not public.may_see_analytics() then
    raise exception 'You do not have permission to read the website analytics.';
  end if;
  if p_from is null or p_to is null then return null; end if;
  p_tz := coalesce(nullif(p_tz, ''), 'UTC');

  v_today   := (now() at time zone p_tz)::date;
  v_to      := least(p_to, v_today);           -- tomorrow has no traffic yet
  v_last    := least(v_to, v_today - 1);
  v_partial := (v_to >= v_today and p_from <= v_today);
  v_ps      := (v_today::timestamp) at time zone p_tz;
  v_pe      := now();

  perform public.site_rollup_range(p_from, v_last, p_tz);

  select coalesce(sum(visits), 0)          as visits,
         coalesce(sum(page_views), 0)      as page_views,
         coalesce(sum(product_views), 0)   as product_views,
         coalesce(sum(add_to_cart), 0)     as add_to_cart,
         coalesce(sum(checkout_starts), 0) as checkout_starts,
         coalesce(sum(mobile), 0)          as mobile,
         coalesce(sum(desktop), 0)         as desktop,
         coalesce(sum(tablet), 0)          as tablet
    into r_sum
    from public.site_daily
   where tz = p_tz and day >= p_from and day <= v_last;

  select count(distinct e.session)                                             as visits,
         count(*) filter (where e.kind = 'page_view')                          as page_views,
         count(*) filter (where e.kind = 'product_view')                       as product_views,
         count(*) filter (where e.kind = 'add_to_cart')                        as add_to_cart,
         count(*) filter (where e.kind = 'checkout_start')                     as checkout_starts,
         count(distinct e.session) filter (where e.device = 'mobile')          as mobile,
         count(distinct e.session) filter (where e.device = 'desktop')         as desktop,
         count(distinct e.session) filter (where e.device = 'tablet')          as tablet
    into r_now
    from public.site_events e
   where v_partial and e.at >= v_ps and e.at < v_pe;

  -- People, which is the one thing that cannot be added up. A browser
  -- seen on Monday and again on Tuesday is two rows in
  -- site_visitor_days and one visitor over the week, and this is where
  -- that is settled.
  select count(*), count(*) filter (where m.is_first)
    into v_people, v_new
    from (
      select u.visitor, bool_or(u.is_first) as is_first
        from (
            select d.visitor, d.is_first
              from public.site_visitor_days d
             where d.day >= p_from and d.day <= v_last
          union all
            -- Today, which has no summary yet. A browser with no row on
            -- any earlier day is here for the first time.
            select e.visitor,
                   not exists (select 1 from public.site_visitor_days x
                                where x.visitor = e.visitor)
              from public.site_events e
             where v_partial and e.at >= v_ps and e.at < v_pe
             group by e.visitor
        ) u
       group by u.visitor
    ) m;

  return json_build_object(
    'from',            p_from,
    'to',              v_to,
    'tz',              p_tz,
    'visits',          r_sum.visits          + coalesce(r_now.visits, 0),
    'page_views',      r_sum.page_views      + coalesce(r_now.page_views, 0),
    'product_views',   r_sum.product_views   + coalesce(r_now.product_views, 0),
    'add_to_cart',     r_sum.add_to_cart     + coalesce(r_now.add_to_cart, 0),
    'checkout_starts', r_sum.checkout_starts + coalesce(r_now.checkout_starts, 0),
    'visitors',        v_people,
    'new_visitors',    v_new,
    -- Not stored, and deliberately not stored: it is the other two
    -- subtracted, and a third number that can disagree with them is a
    -- third number that eventually will.
    'returning_visitors', greatest(v_people - v_new, 0),
    'mobile',          r_sum.mobile  + coalesce(r_now.mobile, 0),
    'desktop',         r_sum.desktop + coalesce(r_now.desktop, 0),
    'tablet',          r_sum.tablet  + coalesce(r_now.tablet, 0)
  );
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 9. The line on the chart.
--
-- One point per day, week, month or year. Same rule as the cards: the
-- days that are over come from the summaries, the day still running is
-- read raw. Visitors are counted across each bucket rather than added
-- up, so a week's figure is people and not visits wearing their name.
--
-- Buckets with no traffic are NOT returned. The admin draws the whole
-- calendar and fills the gaps with nought, because it knows which days
-- the range covers and this does not have to guess.
-- ---------------------------------------------------------------------
create or replace function public.site_series(p_from date, p_to date, p_tz text, p_grain text)
returns json
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_today   date;
  v_to      date;
  v_last    date;
  v_partial boolean;
  v_ps      timestamptz;
  v_pe      timestamptz;
  v_grain   text;
  v_out     json;
begin
  if not public.may_see_analytics() then
    raise exception 'You do not have permission to read the website analytics.';
  end if;
  if p_from is null or p_to is null then return '[]'::json; end if;
  p_tz := coalesce(nullif(p_tz, ''), 'UTC');

  -- Checked against a list rather than passed through. date_trunc takes
  -- its field as text, and text that arrived from a browser is not
  -- something to hand to it unread.
  v_grain := lower(coalesce(p_grain, 'day'));
  if v_grain not in ('day', 'week', 'month', 'year') then v_grain := 'day'; end if;

  v_today   := (now() at time zone p_tz)::date;
  v_to      := least(p_to, v_today);
  v_last    := least(v_to, v_today - 1);
  v_partial := (v_to >= v_today and p_from <= v_today);
  v_ps      := (v_today::timestamp) at time zone p_tz;
  v_pe      := now();

  perform public.site_rollup_range(p_from, v_last, p_tz);

  with counted as (
      select d.day, d.visits, d.page_views, d.product_views,
             d.add_to_cart, d.checkout_starts
        from public.site_daily d
       where d.tz = p_tz and d.day >= p_from and d.day <= v_last
    union all
      select v_today,
             count(distinct e.session),
             count(*) filter (where e.kind = 'page_view'),
             count(*) filter (where e.kind = 'product_view'),
             count(*) filter (where e.kind = 'add_to_cart'),
             count(*) filter (where e.kind = 'checkout_start')
        from public.site_events e
       where v_partial and e.at >= v_ps and e.at < v_pe
      having v_partial
  ),
  -- The visitors of every day in range, summarised days and today
  -- together, so a bucket spanning both counts a browser once.
  people as (
      select d.day, d.visitor
        from public.site_visitor_days d
       where d.day >= p_from and d.day <= v_last
    union all
      select v_today, e.visitor
        from public.site_events e
       where v_partial and e.at >= v_ps and e.at < v_pe
       group by e.visitor
  ),
  bucketed as (
    select date_trunc(v_grain, day::timestamp)::date as bucket,
           sum(visits)          as visits,
           sum(page_views)      as page_views,
           sum(product_views)   as product_views,
           sum(add_to_cart)     as add_to_cart,
           sum(checkout_starts) as checkout_starts
      from counted group by 1
  ),
  heads as (
    select date_trunc(v_grain, day::timestamp)::date as bucket,
           count(distinct visitor) as visitors
      from people group by 1
  )
  select json_agg(json_build_object(
           'bucket',          b.bucket,
           'visits',          coalesce(b.visits, 0),
           'visitors',        coalesce(h.visitors, 0),
           'page_views',      coalesce(b.page_views, 0),
           'product_views',   coalesce(b.product_views, 0),
           'add_to_cart',     coalesce(b.add_to_cart, 0),
           'checkout_starts', coalesce(b.checkout_starts, 0)
         ) order by b.bucket)
    into v_out
    from bucketed b
    left join heads h on h.bucket = b.bucket;

  return coalesce(v_out, '[]'::json);
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 10. What was looked at most.
--
-- These two read the raw table rather than a summary, and that is a
-- decision rather than an oversight: a summary per page per day is a
-- fourth and fifth table to keep in step for a list of ten lines. The
-- read is bounded by the range and led by the `at` index, and the
-- retention below is set so that every range the admin offers — out to
-- a whole year — is still answerable from raw.
-- ---------------------------------------------------------------------
create or replace function public.site_top_pages(p_from date, p_to date, p_tz text, p_limit integer default 10)
returns json
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_start timestamptz;
  v_end   timestamptz;
  v_out   json;
begin
  if not public.may_see_analytics() then
    raise exception 'You do not have permission to read the website analytics.';
  end if;
  if p_from is null or p_to is null then return '[]'::json; end if;
  p_tz    := coalesce(nullif(p_tz, ''), 'UTC');
  v_start := (p_from::timestamp) at time zone p_tz;
  v_end   := ((p_to + 1)::timestamp) at time zone p_tz;

  select json_agg(x order by x.views desc)
    into v_out
    from (
      select coalesce(e.path, '/')      as path,
             min(e.label)               as label,
             count(*)                   as views,
             count(distinct e.visitor)  as visitors
        from public.site_events e
       where e.kind = 'page_view' and e.at >= v_start and e.at < v_end
       group by coalesce(e.path, '/')
       order by count(*) desc
       limit greatest(coalesce(p_limit, 10), 1)
    ) x;

  return coalesce(v_out, '[]'::json);
end;
$$;

create or replace function public.site_top_products(p_from date, p_to date, p_tz text, p_limit integer default 10)
returns json
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_start timestamptz;
  v_end   timestamptz;
  v_out   json;
begin
  if not public.may_see_analytics() then
    raise exception 'You do not have permission to read the website analytics.';
  end if;
  if p_from is null or p_to is null then return '[]'::json; end if;
  p_tz    := coalesce(nullif(p_tz, ''), 'UTC');
  v_start := (p_from::timestamp) at time zone p_tz;
  v_end   := ((p_to + 1)::timestamp) at time zone p_tz;

  select json_agg(x order by x.views desc)
    into v_out
    from (
      select e.sku                                                 as sku,
             min(e.label)                                          as label,
             count(*) filter (where e.kind = 'product_view')       as views,
             count(*) filter (where e.kind = 'add_to_cart')        as carts,
             count(distinct e.visitor)
               filter (where e.kind = 'product_view')              as visitors
        from public.site_events e
       where e.sku is not null and e.at >= v_start and e.at < v_end
       group by e.sku
       order by count(*) filter (where e.kind = 'product_view') desc
       limit greatest(coalesce(p_limit, 10), 1)
    ) x;

  return coalesce(v_out, '[]'::json);
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 11. How many people are on the site now.
--
-- Visits whose tab beat within the last five minutes. It clears out
-- anything older than half an hour as it goes, which is what keeps this
-- table small without a scheduler: the only thing that ever reads it is
-- an administrator with the page open, and that is often enough.
--
-- HONEST ABOUT WHAT IT IS. A browser that is closed stops beating and
-- disappears within five minutes; one left open on a phone in a pocket
-- stops beating too, because the tab is not in front of anybody. It is
-- "how many people are looking right now", not "how many tabs exist".
-- ---------------------------------------------------------------------
create or replace function public.site_live()
returns integer
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.may_see_analytics() then
    raise exception 'You do not have permission to read the website analytics.';
  end if;

  delete from public.site_presence where seen_at < now() - interval '30 minutes';

  select count(*) into v_count
    from public.site_presence
   where seen_at > now() - interval '5 minutes';

  return coalesce(v_count, 0);
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 12. Throwing away what is no longer needed.
--
-- The summaries are the history and they are never pruned. The raw rows
-- behind them are what gets large, and 400 days is chosen so that every
-- range the admin can ask for — out to a whole year, plus a month of
-- room — is still answerable from raw.
--
-- IT WILL NOT PRUNE A DAY THAT HAS NOT BEEN SUMMED UP. Whatever is
-- asked for, the cut never goes past the last day with a summary row,
-- so raw data can never be deleted before the thing that replaces it
-- exists. Nothing calls this on a schedule; run it when you want to,
-- or never.
-- ---------------------------------------------------------------------
create or replace function public.site_prune(p_days integer default 400, p_tz text default 'UTC')
returns integer
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_asked  timestamptz;
  v_summed date;
  v_cut    timestamptz;
  v_gone   integer := 0;
begin
  if not public.may_see_analytics() then
    raise exception 'You do not have permission to prune the website analytics.';
  end if;
  p_tz    := coalesce(nullif(p_tz, ''), 'UTC');
  v_asked := now() - (greatest(coalesce(p_days, 400), 30) || ' days')::interval;

  select max(day) into v_summed from public.site_daily;
  if v_summed is null then return 0; end if;

  v_cut := least(v_asked, ((v_summed + 1)::timestamp) at time zone p_tz);

  delete from public.site_events where at < v_cut;
  get diagnostics v_gone = row_count;

  delete from public.site_presence where seen_at < now() - interval '1 day';

  return v_gone;
end;
$$;


-- ---------------------------------------------------------------------
-- STEP 13. Who may run any of this.
--
-- Every one of them is SECURITY DEFINER and every one asks
-- may_see_analytics() as its first line, so the grant is to signed-in
-- accounts and the answer is still no for anybody without the tick.
-- The two rollup functions are not granted at all: nothing outside this
-- file calls them, and the reading functions run them as their definer.
-- ---------------------------------------------------------------------
revoke all on function public.may_see_analytics()                          from public;
revoke all on function public.site_beat(text, text)                        from public;
revoke all on function public.site_rollup(date, text)                      from public;
revoke all on function public.site_rollup_range(date, date, text)          from public;
revoke all on function public.site_stats(date, date, text)                 from public;
revoke all on function public.site_series(date, date, text, text)          from public;
revoke all on function public.site_top_pages(date, date, text, integer)    from public;
revoke all on function public.site_top_products(date, date, text, integer) from public;
revoke all on function public.site_live()                                  from public;
revoke all on function public.site_prune(integer, text)                    from public;

-- The heartbeat is the one function a visitor may run. It writes one
-- timestamp and returns nothing.
grant execute on function public.site_beat(text, text)                        to anon, authenticated;
grant execute on function public.may_see_analytics()                          to authenticated;
grant execute on function public.site_stats(date, date, text)                 to authenticated;
grant execute on function public.site_series(date, date, text, text)          to authenticated;
grant execute on function public.site_top_pages(date, date, text, integer)    to authenticated;
grant execute on function public.site_top_products(date, date, text, integer) to authenticated;
grant execute on function public.site_live()                                  to authenticated;
grant execute on function public.site_prune(integer, text)                    to authenticated;


-- ---------------------------------------------------------------------
-- STEP 14. The tick in Settings > Users & Roles.
--
-- Website Analytics is a new thing a role may be given, and phase 10
-- seeded the roles row before it existed. This adds the key to any role
-- that has no opinion about it yet, and to no other.
--
-- WHAT IT DEFAULTS TO, and why. The same answer that role already has
-- for Dashboard. Both are the storefront at a glance and neither
-- changes anything, so a role trusted with one is trusted with the
-- other — which gives Administrator the analytics and leaves Agent, who
-- only answers chats, exactly as they were. A role that has already
-- been given or refused it is left alone, so running this file again
-- never undoes a decision made in Settings.
--
-- RUN THIS AFTER supabase-chat-phase10.sql. Before it there is no roles
-- row and this quietly does nothing; running this file again afterwards
-- puts it right.
-- ---------------------------------------------------------------------
update public.site_settings s
   set data = (
     select jsonb_object_agg(
              role_key,
              case
                when role_def ? 'permissions'
                 and not (role_def->'permissions' ? 'analytics')
                then jsonb_set(role_def, '{permissions,analytics}',
                               coalesce(role_def->'permissions'->'dashboard', 'false'::jsonb))
                else role_def
              end)
       from jsonb_each(s.data) as roles(role_key, role_def))
 where s.key = 'roles'
   and jsonb_typeof(s.data) = 'object'
   and exists (
     select 1 from jsonb_each(s.data) as roles(role_key, role_def)
      where role_def ? 'permissions'
        and not (role_def->'permissions' ? 'analytics'));

-- The owner is never limited by a role — my_access() hands them
-- everything and the admin page short-circuits every check for them —
-- so nothing above needs to change for the shop owner, and my_access()
-- is deliberately left exactly as phase 10 wrote it.

notify pgrst, 'reload schema';


-- ---------------------------------------------------------------------
-- STEP 15. Check it.
-- ---------------------------------------------------------------------
select table_name as created
  from information_schema.tables
 where table_schema = 'public'
   and table_name in ('site_events', 'site_daily', 'site_visitor_days', 'site_presence')
 order by table_name;
-- Expect four rows.

select routine_name as installed
  from information_schema.routines
 where routine_schema = 'public'
   and routine_name in ('may_see_analytics', 'site_beat', 'site_rollup',
                        'site_rollup_range', 'site_stats', 'site_series',
                        'site_top_pages', 'site_top_products', 'site_live',
                        'site_prune')
 order by routine_name;
-- Expect ten rows.

select role_key as role, role_def->'permissions'->>'analytics' as website_analytics
  from public.site_settings s, jsonb_each(s.data) as roles(role_key, role_def)
 where s.key = 'roles';
-- Expect one line per role, each saying true or false and none saying
-- nothing at all. A role with no answer means this file was run before
-- supabase-chat-phase10.sql — run it again and the line fills in.


-- =====================================================================
-- THERE IS NOTHING TO SET UP
--
-- No environment variable, no key, no scheduled function. The storefront
-- records through the same public key it already uses for the chat and
-- the reviews, and the admin reads through the session of whoever is
-- signed in. If this file is never run, the storefront's tracker finds
-- no table, stops asking, and the website behaves exactly as it does
-- now — see assets/analytics.js, which is built to fail silent.
--
-- TO UNDO ALL OF IT
--
--   drop table if exists public.site_events;
--   drop table if exists public.site_daily;
--   drop table if exists public.site_visitor_days;
--   drop table if exists public.site_presence;
--   drop function if exists public.site_stats(date, date, text);
--   drop function if exists public.site_series(date, date, text, text);
--   drop function if exists public.site_top_pages(date, date, text, integer);
--   drop function if exists public.site_top_products(date, date, text, integer);
--   drop function if exists public.site_live();
--   drop function if exists public.site_prune(integer, text);
--   drop function if exists public.site_rollup(date, text);
--   drop function if exists public.site_rollup_range(date, date, text);
--   drop function if exists public.site_beat(text, text);
--   drop function if exists public.may_see_analytics();
--
-- Nothing else in the database refers to any of it, and the Analytics
-- tab tells the shop the table is missing rather than showing an error.
-- =====================================================================
