-- An old table, made before sku existed, and a Supabase-like publication.
create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  at timestamptz not null default now(), kind text not null, path text, label text,
  visitor text not null, session text not null, device text,
  is_new boolean not null default false, referrer text);
do $$ begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
end $$;
